### ISSUE TITLE
Question: Compiling With MinGW & Visual Studio 2015

### ISSUE THREAD

**Issue by NoMoreFood** [sunqueen/vlc-2.2.4.32-2013#1]
With some minor tweaks, I was able to get this to compile but not link under Visual Studio 2015.  I'm having some linking errors that I believe are related to MinGW not being compiled with Visual Studio.  Where did the static libraries such as libmingw32.lib come from?

**Comment by sunqueen** [comment]
Please choose "Platform toolset" to Visual studio 2013(v120).
This is easy way.
I'll try to find more best way.
If I find good solution, I comment that. ^^

**Comment by hoowang** [comment]
请教一下仁兄，怎么编译可以支持直接用visual studio ide打开？有具体的文档吗，如果有，希望能给一份参考，按照官方wiki编译出来的应该没有.sln文件吧？非常感谢！

**Comment by sunqueen** [comment]
Hi.
I'm sorry.
It's late.
I was found this mail, today.
Can you explain with english?
I was translation your comment, but I don't understand.
I'm very sorry.
I'm korean. ^^

**Comment by sunqueen** [comment]
Hi.
I think your question is related with previous question.
I attached screen capture to setting visual studio.
![visual_studio-2015](https://user-images.githubusercontent.com/3523606/27253038-a365b36a-53a6-11e7-8c7d-fe002269ac6a.PNG)

**Comment by hoowang** [comment]
My dear friends, hello, thank you very much for your reply, I want to know how to compile vlc2.2.6, compile later can have a visual studio2015 .sln file.Can you tell me a way, of course, if you have already compiled here 2.2.6 version of VLC project, hope you can give me a copy.Give you the best blessing, thank you ~

**Comment by sunqueen** [comment]
Hi. hoowang.
Sorry. I was not to make that version.
If I make that. I'll give you that.
But I'm not sure.
Bye ~~~ ^^

**Comment by sunqueen** [comment]
Hi.

This is vlc-2.2.6 for VS.

vlc-2.2.6 compile with VS2013 update 4
https://github.com/sunqueen/vlc-2.2.6.32-2013.git

vlc-2.2.6 compile with VS2015
https://github.com/sunqueen/vlc-2.2.6.32-2015.git

VS215 version, don't upgrade at first. ^^

Bye.

**Comment by hoowang** [comment]
非常感谢，仁兄，花时间帮助编译vlc for 2015 我十分地感激，祈愿你吉祥如意！
Thank you very much, brother. I really appreciate your time and help to compile VLC for 2015. I wish you good luck!

**Comment by laixiboy** [comment]
Thanks very much for sharing your achievement with us.

**Comment by sunqueen** [comment]
It's my pleasure.

**Comment by hoowang** [comment]
hi, my dear friend,I need your help，I had these errors when I compiled the release version，Please help me . error info in image attach files：
![jietu20171007-224751 2x](https://user-images.githubusercontent.com/7238995/31309058-b93f6a3c-abb2-11e7-8f10-de3c80729d72.jpg)
![jietu20171007-224816 2x](https://user-images.githubusercontent.com/7238995/31309059-b99288ac-abb2-11e7-96e9-284df6bd5821.jpg)

The project I chose link is:https://github.com/sunqueen/vlc-2.2.6.32-2013.git

**Comment by sunqueen** [comment]
Hi.

Please check your directorys.
It looks you don't have all source.
vlc_common.h is exist file of include folder in project.

**Comment by hoowang** [comment]
May be the reason for the project configuration，because debug configuration version is compile success.I changed part of the configuration for release version,But there are some errors, please help me.Thanks very much.

无法解析的外部符号（An unparsed external symbol）

![jietu20171008-211031 2x](https://user-images.githubusercontent.com/7238995/31317209-8c45d918-ac6f-11e7-904d-a84ad11dac59.jpg)

**Comment by sunqueen** [comment]
If you want to compile with release version.
Check all configuration of projects.
Sorry. I was not support release version. :(

**Comment by hoowang** [comment]
Can you help me configuration can be compiled in release version, I try to configure a complete project, and eliminate all the compiler error, but the rest of the linker error, I feel helpless, please help, thank you ~

**Comment by sunqueen** [comment]
Hi.
I'm very sorry.
I don't have plan to support release version.
Why do you make release version?
That is not fast and full hd is not played.
If you want to use libvlc, I recommand to use original version of VLC.

**Comment by hoowang** [comment]
hi,Could you please do me a favor, I really can't find a good way to solve the problem of unable to compile the release version, I need to make some changes with the help of the project after used for a public software project and non-commercial project. The purpose of compiling the release is to enable the compiler to optimize the code so that it outputs more binary efficiency. Please help me, please, if you come to China, I can take you to some nice places. Thank you very much😊😊😊

**Comment by sunqueen** [comment]
Sorry.
I'm pretty much busy, this days. :(

**Comment by hoowang** [comment]
I am very sorry to disturb you again and again, this matter is not urgent, if you can, I hope you can help me after this time. Thank you very much.😊😊😊
